import fs from "node:fs/promises";
import { watch } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PATTERNS_DIR = path.resolve(__dirname, "../src/patterns");

const isWatchMode = process.argv.includes("--watch");

/**
 * Scan for .md files in src/patterns and generate .gen.ts files
 */
async function syncMarkdown() {
  console.log("Syncing markdown files...");

  try {
    const files = await fs.readdir(PATTERNS_DIR);
    const mdFiles = files.filter((file) => file.endsWith(".md"));

    if (mdFiles.length === 0) {
      console.log("No markdown files found.");
    } else {
      for (const mdFile of mdFiles) {
        await generateTsFile(mdFile);
      }
      console.log(`Successfully synced ${mdFiles.length} markdown files.`);
    }

    if (isWatchMode) {
      console.log(`Watching for changes in ${PATTERNS_DIR}...`);
      watch(PATTERNS_DIR, { recursive: false }, (eventType, filename) => {
        if (filename && filename.endsWith(".md")) {
          console.log(`File changed: ${filename}`);
          generateTsFile(filename).catch((err) =>
            console.error(`Error regenerating ${filename}:`, err),
          );
        }
      });
      // Keep process alive
      await new Promise(() => {});
    }
  } catch (error) {
    console.error("Failed to sync markdown files:", error);
    process.exit(1);
  }
}

async function generateTsFile(mdFilename: string) {
  const mdPath = path.join(PATTERNS_DIR, mdFilename);
  const basename = path.basename(mdFilename, ".md");
  const tsFilename = `${basename}.gen.ts`;
  const tsPath = path.join(PATTERNS_DIR, tsFilename);

  try {
    const content = await fs.readFile(mdPath, "utf-8");

    // Create variable name from filename (e.g. pattern13 -> pattern13Content)
    const varName = `${basename}Content`;

    const tsContent = `// This file is auto-generated by scripts/sync-markdown.ts
// Do not edit this file directly.

export const ${varName} = ${JSON.stringify(content)};
`;

    await fs.writeFile(tsPath, tsContent, "utf-8");
    console.log(`Generated ${tsFilename}`);
  } catch (error) {
    console.error(`Failed to read/write for ${mdFilename}`, error);
  }
}

syncMarkdown();
