import fs from "node:fs/promises";
import { watch } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PATTERNS_DIR = path.resolve(__dirname, "../src/patterns");

const isWatchMode = process.argv.includes("--watch");

/**
 * Scan for directories in src/patterns containing ja.md
 */
async function syncMarkdown() {
  console.log("Syncing markdown files...");

  try {
    const entries = await fs.readdir(PATTERNS_DIR, { withFileTypes: true });

    // Find directories that look like patterns (not files, not starting with .)
    const patternDirs = entries
      .filter((entry) => entry.isDirectory() && !entry.name.startsWith("."))
      .map((entry) => entry.name);

    if (patternDirs.length === 0) {
      console.log("No pattern directories found.");
    } else {
      const validSlugs: string[] = [];
      for (const slug of patternDirs) {
        const success = await generateTsFile(slug);
        if (success) {
          validSlugs.push(slug);
        }
      }
      await generateRootIndexFile(validSlugs);
      console.log(`Successfully synced ${validSlugs.length} patterns.`);
    }

    if (isWatchMode) {
      console.log(`Watching for changes in ${PATTERNS_DIR}...`);
      watch(PATTERNS_DIR, { recursive: true }, async (eventType, filename) => {
        if (!filename) return;

        // Check if the change happened inside a pattern directory
        // filename looks like "pattern13/ja.md" or "pattern13/index.ts"
        const parts = filename.split(path.sep);
        if (parts.length >= 2) {
          const slug = parts[0];
          const file = parts[parts.length - 1]; // e.g. ja.md

          if (file === "ja.md") {
            console.log(`File changed: ${filename}`);
            const success = await generateTsFile(slug);
            if (success) {
              // We might need to regenerate root index if a new pattern was added (though watch mode usually catches existing ones)
              // For simplicity in watch mode, strictly regenerating root index might be overkill if we just edit content,
              // but if we add a new folder it matters.
              // However, fs.watch on parent dir should catch generated index.ts changes too, avoiding loops is key.
              // For now, let's just regenerate the specific file.
              // If we want to support adding new directories in watch mode, we need to scan again.
            }
          }
        }
      });
      // Keep process alive
      await new Promise(() => {});
    }
  } catch (error) {
    console.error("Failed to sync markdown files:", error);
    process.exit(1);
  }
}

async function generateRootIndexFile(slugs: string[]) {
  const indexContent = `// This file is auto-generated by scripts/sync-markdown.ts
// Do not edit this file directly.

${slugs.map((slug) => `import { ${slug} } from "./${slug}";`).join("\n")}

${slugs.map((slug) => `export * from "./${slug}";`).join("\n")}

export const allPatterns = [
${slugs.map((slug) => `  ${slug},`).join("\n")}
];
`;

  const indexPath = path.join(PATTERNS_DIR, "index.ts");
  await fs.writeFile(indexPath, indexContent, "utf-8");
  console.log(`Generated patterns/index.ts`);
}

async function generateTsFile(slug: string): Promise<boolean> {
  const patternDir = path.join(PATTERNS_DIR, slug);
  const mdPath = path.join(patternDir, "ja.md");
  const tsPath = path.join(patternDir, "index.ts");

  try {
    // Check if ja.md exists
    try {
      await fs.access(mdPath);
    } catch {
      // Skip if no ja.md found (maybe just an empty dir or unrelated dir)
      return false;
    }

    const content = await fs.readFile(mdPath, "utf-8");

    // Variable name logic: pattern13 -> pattern13Content (backward compatibility)
    // Also export a structured object
    const legacyVarName = `${slug}Content`;

    const tsContent = `// This file is auto-generated by scripts/sync-markdown.ts
// Do not edit this file directly.

export const ${legacyVarName} = ${JSON.stringify(content)};

export const ${slug} = {
  slug: "${slug}",
  ja: ${legacyVarName},
} as const;
`;

    await fs.writeFile(tsPath, tsContent, "utf-8");
    console.log(`Generated ${path.join(slug, "index.ts")}`);
    return true;
  } catch (error) {
    console.error(`Failed to generate TS for ${slug}`, error);
    return false;
  }
}

syncMarkdown();
