import fs from "node:fs/promises";
import { watch } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SRC_DIR = path.resolve(__dirname, "../src");

const CATEGORIES = ["patterns", "basics"];

const isWatchMode = process.argv.includes("--watch");

/**
 * Scan for directories in src/{category} containing ja.md
 */
async function syncMarkdown() {
  console.log("Syncing markdown files...");

  try {
    for (const category of CATEGORIES) {
      await syncCategory(category);
    }

    if (isWatchMode) {
      console.log(`Watching for changes in ${SRC_DIR}...`);
      watch(SRC_DIR, { recursive: true }, async (eventType, filename) => {
        if (!filename) return;

        // filename looks like "patterns/p13/ja.md"
        const parts = filename.split(path.sep);
        if (parts.length >= 3) {
          const category = parts[0];
          const slug = parts[1];
          const file = parts[parts.length - 1]; // e.g. ja.md

          if (CATEGORIES.includes(category) && file === "ja.md") {
            console.log(`File changed: ${filename}`);
            const success = await generateTsFile(category, slug);
            if (success) {
              // Update index if needed (simplified: always update root index for now or rely on specific command)
              // regenerating root index for category
              const categoryDir = path.join(SRC_DIR, category);
              const entries = await fs.readdir(categoryDir, {
                withFileTypes: true,
              });
              const validSlugs = entries
                .filter((e) => e.isDirectory() && !e.name.startsWith("."))
                .map((e) => e.name);
              await generateRootIndexFile(category, validSlugs);
            }
          }
        }
      });
      // Keep process alive
      await new Promise(() => {});
    }
  } catch (error) {
    console.error("Failed to sync markdown files:", error);
    process.exit(1);
  }
}

async function syncCategory(category: string) {
  const categoryDir = path.join(SRC_DIR, category);

  // Ensure category dir exists
  try {
    await fs.access(categoryDir);
  } catch {
    // Create if not exists? Or just skip/warn?
    // Let's create it to be safe or just skip
    console.log(`Category directory ${category} does not exist, creating...`);
    await fs.mkdir(categoryDir, { recursive: true });
  }

  const entries = await fs.readdir(categoryDir, { withFileTypes: true });

  // Find directories that look like content
  const slugDirs = entries
    .filter((entry) => entry.isDirectory() && !entry.name.startsWith("."))
    .map((entry) => entry.name);

  if (slugDirs.length === 0) {
    console.log(`No content found in ${category}.`);
  } else {
    const validSlugs: string[] = [];
    for (const slug of slugDirs) {
      const success = await generateTsFile(category, slug);
      if (success) {
        validSlugs.push(slug);
      }
    }
    await generateRootIndexFile(category, validSlugs);
    console.log(
      `Successfully synced ${validSlugs.length} items in ${category}.`,
    );
  }
}

function slugToVarName(slug: string): string {
  return slug.replace(/-([a-z])/g, (g) => g[1].toUpperCase());
}

async function generateRootIndexFile(category: string, slugs: string[]) {
  // capitalize category name for export (e.g. allPatterns, allBasics)
  const capitalizedCategory =
    category.charAt(0).toUpperCase() + category.slice(1);
  const arrayName = `all${capitalizedCategory}`;

  const indexContent = `// This file is auto-generated by scripts/sync-markdown.ts
// Do not edit this file directly.

${slugs.map((slug) => `import { ${slugToVarName(slug)} } from "./${slug}";`).join("\n")}

${slugs.map((slug) => `export * from "./${slug}";`).join("\n")}

export const ${arrayName} = [
${slugs.map((slug) => `  ${slugToVarName(slug)},`).join("\n")}
];
`;

  const indexPath = path.join(SRC_DIR, category, "index.ts");
  await fs.writeFile(indexPath, indexContent, "utf-8");
  console.log(`Generated ${category}/index.ts`);
}

async function generateTsFile(
  category: string,
  slug: string,
): Promise<boolean> {
  const dirPath = path.join(SRC_DIR, category, slug);
  const mdPath = path.join(dirPath, "ja.md");
  const tsPath = path.join(dirPath, "index.ts");

  try {
    try {
      await fs.access(mdPath);
    } catch {
      return false;
    }

    const content = await fs.readFile(mdPath, "utf-8");

    const varName = slugToVarName(slug);

    // Legacy support logic: only for pattern13->p13 case?
    // Actually, for new contents like basic articles, we don't strictly need legacy "content" var.
    // But consistency is good.
    const contentVarName = `${varName}Content`;

    const tsContent = `// This file is auto-generated by scripts/sync-markdown.ts
// Do not edit this file directly.

export const ${contentVarName} = ${JSON.stringify(content)};

export const ${varName} = {
  slug: "${slug}",
  ja: ${contentVarName},
} as const;
`;

    await fs.writeFile(tsPath, tsContent, "utf-8");
    console.log(`Generated ${path.join(category, slug, "index.ts")}`);
    return true;
  } catch (error) {
    console.error(`Failed to generate TS for ${category}/${slug}`, error);
    return false;
  }
}

syncMarkdown();
