// This file is auto-generated by scripts/sync-markdown.ts
// Do not edit this file directly.

import { pattern13 } from "./pattern13";

export * from "./pattern13";

export const allPatterns = [pattern13];
