// This file is auto-generated by scripts/sync-markdown.ts
// Do not edit this file directly.

import { howToLearn } from "./how-to-learn";

export * from "./how-to-learn";

export const allBasics = [howToLearn];
