// This file is auto-generated by scripts/sync-markdown.ts
// Do not edit this file directly.

import { howToLearn } from "./how-to-learn";
import { patternNaming } from "./pattern-naming";

export * from "./how-to-learn";
export * from "./pattern-naming";

export const allBasics = [howToLearn, patternNaming];
